dist: xenial
os: linux
language: cpp
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install libboost-test-dev -y
- pushd ~
- git clone https://github.com/google/googletest.git
- cd googletest
- mkdir build && cd build
- cmake .. -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr
- make -j8
- sudo make install
- sudo ldconfig
- echo "finish prepare"
- popd
- "export AK_CUR_REPO_NAME=`echo ${TRAVIS_REPO_SLUG}|awk -F/ '{print $2;}'`"
script:
- cmake . -DAK_DEB_PKG_NAME=${AK_CUR_REPO_NAME}
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
before_deploy:
- "chmod +x before_deploy.sh"
- ./before_deploy.sh
deploy:
   provider: script
   skip_cleanup: true
   script:
   - curl -T ${AK_CUR_REPO_NAME}-0.0.${TRAVIS_BUILD_NUMBER}-Linux.deb -ualex-stch:$BINTRAY_API_KEY "https://api.bintray.com/content/alex-stch/otuscpp/${AK_CUR_REPO_NAME}/${TRAVIS_BUILD_NUMBER}/${AK_CUR_REPO_NAME}-0.0.${TRAVIS_BUILD_NUMBER}-Linux.deb;deb_distribution=${TRAVIS_DIST};deb_component=main;deb_architecture=amd64;publish=1"
