dist: xenial
os: linux
language: cpp
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install libboost-test-dev -y
- pushd ~
- git clone https://github.com/google/googletest.git
- cd googletest
- mkdir build && cd build
- cmake .. -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr
- make -j8
- sudo make install
- sudo ldconfig
- echo "finish prepare"
- popd
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
before_deploy:
- "chmod +x before_deploy.sh"
- ./before_deploy.sh
- "echo ${TRAVIS_DIST}"
deploy:
   provider: script
   skip_cleanup: true
   script:
   - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ualex-stch:$BINTRAY_API_KEY "https://api.bintray.com/content/alex-stch/otuscpp/${TRAVIS_BRANCH}/${TRAVIS_BUILD_NUMBER}/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"